[atomselect top "resname GE01 and name CAA"] set name CAA
[atomselect top "resname GE01 and name CAB"] set name CAB
[atomselect top "resname GE01 and name CAC"] set name CAC
[atomselect top "resname GE01 and name CAD"] set name CAD
[atomselect top "resname GE01 and name CBM"] set name CBM
[atomselect top "resname GE01 and name CBN"] set name CBN
[atomselect top "resname GE01 and name CBO"] set name CBO
[atomselect top "resname GE01 and name CBP"] set name CBP
[atomselect top "resname GE01 and name CBQ"] set name CBQ
[atomselect top "resname GE01 and name CBR"] set name CBR
[atomselect top "resname GE01 and name CBS"] set name CBS
[atomselect top "resname GE01 and name CBT"] set name CBT
[atomselect top "resname GE01 and name CBU"] set name CBU
[atomselect top "resname GE01 and name CBV"] set name CBV
[atomselect top "resname GE01 and name CBW"] set name CBW
[atomselect top "resname GE01 and name CBX"] set name CBX
[atomselect top "resname GE01 and name CBY"] set name CBY
[atomselect top "resname GE01 and name CBZ"] set name CBZ
[atomselect top "resname GE01 and name CCA"] set name CCA
[atomselect top "resname GE01 and name CCB"] set name CCB
[atomselect top "resname GE01 and name CCC"] set name CCC
[atomselect top "resname GE01 and name CCD"] set name CCD
[atomselect top "resname GE01 and name CCE"] set name CCE
[atomselect top "resname GE01 and name CCF"] set name CCF
[atomselect top "resname GE01 and name CCG"] set name CCG
[atomselect top "resname GE01 and name CCH"] set name CCH
[atomselect top "resname GE01 and name CCI"] set name CCI
[atomselect top "resname GE01 and name CCJ"] set name CCJ
[atomselect top "resname GE01 and name CCK"] set name CCK
[atomselect top "resname GE01 and name CCL"] set name CCL
[atomselect top "resname GE01 and name FAE"] set name FAE
[atomselect top "resname GE01 and name FAF"] set name FAF
[atomselect top "resname GE01 and name FAG"] set name FAG
[atomselect top "resname GE01 and name FAH"] set name FAH
[atomselect top "resname GE01 and name FAI"] set name FAI
[atomselect top "resname GE01 and name FAJ"] set name FAJ
[atomselect top "resname GE01 and name FAK"] set name FAK
[atomselect top "resname GE01 and name FAL"] set name FAL
[atomselect top "resname GE01 and name FAM"] set name FAM
[atomselect top "resname GE01 and name FAN"] set name FAN
[atomselect top "resname GE01 and name FAO"] set name FAO
[atomselect top "resname GE01 and name FAP"] set name FAP
[atomselect top "resname GE01 and name FAQ"] set name FAQ
[atomselect top "resname GE01 and name FAR"] set name FAR
[atomselect top "resname GE01 and name FAS"] set name FAS
[atomselect top "resname GE01 and name FAT"] set name FAT
[atomselect top "resname GE01 and name FAU"] set name FAU
[atomselect top "resname GE01 and name FAV"] set name FAV
[atomselect top "resname GE01 and name FAW"] set name FAW
[atomselect top "resname GE01 and name FAX"] set name FAX
[atomselect top "resname GE01 and name FAY"] set name FAY
[atomselect top "resname GE01 and name FAZ"] set name FAZ
[atomselect top "resname GE01 and name FBA"] set name FBA
[atomselect top "resname GE01 and name FBB"] set name FBB
[atomselect top "resname GE01 and name FBC"] set name FBC
[atomselect top "resname GE01 and name FBD"] set name FBD
[atomselect top "resname GE01 and name FBE"] set name FBE
[atomselect top "resname GE01 and name FBF"] set name FBF
[atomselect top "resname GE01 and name FBG"] set name FBG
[atomselect top "resname GE01 and name FBH"] set name FBH
[atomselect top "resname GE01 and name FBI"] set name FBI
[atomselect top "resname GE01 and name FBJ"] set name FBJ
[atomselect top "resname GE01 and name FBK"] set name FBK
[atomselect top "resname GE01 and name FBL"] set name FBL
[atomselect top "resname GE01 and name HAA"] set name HAA
[atomselect top "resname GE01 and name HAB"] set name HAB
[atomselect top "resname GE01 and name HAC"] set name HAC
[atomselect top "resname GE01 and name HAD"] set name HAD
[atomselect top "resname GE01 and name HAE"] set name HAE
[atomselect top "resname GE01 and name HAF"] set name HAF
[atomselect top "resname GE01 and name HAG"] set name HAG
[atomselect top "resname GE01 and name HAH"] set name HAH
[atomselect top "resname GE01 and name HAI"] set name HAI
[atomselect top "resname GE01 and name HAJ"] set name HAJ
[atomselect top "resname GE01 and name HAK"] set name HAK
[atomselect top "resname GE01 and name HAL"] set name HAL
[atomselect top "resname GE01 and name HB0"] set name HB0
[atomselect top "resname GE01 and name HB1"] set name HB1
[atomselect top "resname GE01 and name HB2"] set name HB2
[atomselect top "resname GE01 and name HB3"] set name HB3
[atomselect top "resname GE01 and name HB4"] set name HB4
[atomselect top "resname GE01 and name HB5"] set name HB5
[atomselect top "resname GE01 and name HBM"] set name HBM
[atomselect top "resname GE01 and name HBN"] set name HBN
[atomselect top "resname GE01 and name HBO"] set name HBO
[atomselect top "resname GE01 and name HBP"] set name HBP
[atomselect top "resname GE01 and name HBQ"] set name HBQ
[atomselect top "resname GE01 and name HBR"] set name HBR
[atomselect top "resname GE01 and name HBS"] set name HBS
[atomselect top "resname GE01 and name HBT"] set name HBT
[atomselect top "resname GE01 and name HBU"] set name HBU
[atomselect top "resname GE01 and name HBV"] set name HBV
[atomselect top "resname GE01 and name HBW"] set name HBW
[atomselect top "resname GE01 and name HBX"] set name HBX
[atomselect top "resname GE01 and name HBY"] set name HBY
[atomselect top "resname GE01 and name HBZ"] set name HBZ
[atomselect top "resname GE01 and name NCM"] set name NCM
[atomselect top "resname GE01 and name NCN"] set name NCN
